transparency/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import *

# define urls of sub-sites
urlpatterns = [
    # main home website
    path('', TemplateView.as_view(template_name="transparency_home.html"), name="transparency_home"),

    # search API
    path("search/", send_searchresults, name="send_searchresults"),
    path("search/filters", send_filters, name="send_filters"),
]

transparency/transparency/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('transparency/admin/', admin.site.urls),
    path('transparency/', include('main.urls')),
    path('transparency/articlesummaries/', include('articlesummaries.urls')),
    path('transparency/projectsummaries/', include('projectsummaries.urls')),
    path('transparency/educationalcontent/', include('educationalcontent.urls')),
    path('transparency/forum/', include('forum.urls')),
    #path('transparency/oidc/', include('keycloak_oidc.urls')),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transparency/forum/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField

from main.globalvariables import AREA_CHOICES


# model for a forum post
class ForumPost(models.Model):
    # initialise fields
    title = models.CharField(max_length=1024)
    authors = models.CharField(max_length=1024)
    url = models.URLField(blank=True) # add validator later
    date_post = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    area1 = models.CharField(max_length=1024, choices=AREA_CHOICES)
    area2 = models.CharField(max_length=1024, choices=AREA_CHOICES, blank=True)
    area3 = models.CharField(max_length=1024, choices=AREA_CHOICES, blank=True)

    text = models.CharField(max_length=1500)

    slug = AutoSlugField(populate_from=['title'])
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True)

    def __str__(self):
        # specify the return text of the str-operator on this class
        return self.title


# model for the answers to a post
class ForumAnswer(models.Model):
    # foreign key to ForumPost
    forumpost = models.ForeignKey(ForumPost, related_name='answers', on_delete=models.CASCADE)

    # initialise fields
    authors = models.CharField(max_length=1024)
    url = models.URLField(blank=True) # add validator later
    date_post  = models.DateTimeField(auto_now_add=True)
    date_modified  = models.DateTimeField(auto_now=True)
    text = models.CharField(max_length=1500)

transparency/templates/app_templates/app_home.html
{% extends 'base.html' %}

{% block content %}

<div>

    <div class="container-flex">
        <div class="row">
            <div class="col-12 col-md-6 bottom-buffer">
                <div>
                    <p class="header-paragraph">{{ header_search }}</p>
                    <p>{{ text_search }}</p>
                </div>

                <br>

                <div>
                    <p class="header-paragraph">Areas</p>
                    <div>
                        <a class="area-link" href="{% url appname|add:'_list' %}">Show all ...</a>
                        {% for area in areas %}
                        <a class="area-link" href="{% url appname|add:'_list' %}?area={{ area.0 }}">{{ area.1 }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        
            <div class="col-12 col-md-6 bottom-buffer">
                <div>
                    <p class="header-paragraph">{{ header_add }}</p>
                    <!--p>If you want to upload your own brief paper summary, click on "New Summary".</p-->
                    <p>{{ text_add }}</p>
                    <!--<a class="link-button" href="{% url 'articlesummaries_readbibtex' %}">BibTex</a>-->
                    <a class="link-button" href="{% url appname|add:'_create' %}">{{ text_button }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

transparency/templates/app_templates/articlesummaries_readbibtex.html
{% extends 'base.html' %}


{% block content %}
<div>
    <form style="width:100%;" id="add-article-summary" method="post" enctype='multipart/form-data'>{% csrf_token %}
        {{ form.as_p }}
        <a class="link-button form-cancel-button" href="javascript:history.back()">Cancel</a>
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock %}

transparency/templates/app_templates/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    <form id="add-entry" method="post" enctype='multipart/form-data'>{% csrf_token %}
        {{ form.as_p }}   

        {% if appname == 'educationalcontent' %}
        <div class="spacer-div"></div>
        <p><strong>Files and videos can be added after creating the course.</strong></p>
        <div class="spacer-div"></div>
        {% endif %}

        <a class="link-button form-cancel-button" href="javascript:history.back()">Cancel</a>
        <input type="submit" value="Submit">
    </form>
</div>

<!-- JavaScript -->
<script type="text/javascript" src="{% static 'assets/transparency/js/create_areaSelects.js' %}"></script>

{% if appname == 'articlesummaries' or appname == 'projectsummaries' %}
<script type="text/javascript" src="{% static 'assets/transparency/js/create_imageCaption.js' %}"></script>
{% endif %}

{% endblock %}

transparency/templates/app_templates/create_foreignKey.html
{% extends 'base.html' %}


{% block content %}
<div>
    <form style="width: 100%;" id="add-article-summary" method="post" enctype='multipart/form-data'>{% csrf_token %}
        {{ form.as_p }}
        <a class="link-button form-cancel-button" href="javascript:history.back()">Cancel</a>
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

transparency/templates/app_templates/delete.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form method="post">{% csrf_token %}
        {% if object.title %}
        <p>Are you sure you want to delete the {{ text_delete }}:</p>
        <p>"{{ object.title }}"</p>
        {% else %}
        <p>Are you sure you want to delete this answer?</p>
        {% endif %}

        <div class="spacer-div"></div>

        <a class="link-button form-cancel-button" href="javascript:history.back()">Cancel</a>
        <input class="form-delete-button" type="submit" value="Delete">
    </form>
</div>
{% endblock %}

transparency/templates/app_templates/detail.html
{% extends 'base.html' %}


{% block content %}
<div>
    <!-- backward-button -->
    <a class="underlined-link" href="{% url appname|add:'_list' %}">&lsaquo; Back</a>

    <!-- element title -->
    <h1 class="no-margin">{{ object.title }}</h1>

    <hr>

    <!-- element information -->
    <div class="container-flex">
        <!-- shown information specified for each app -->
        {% if appname == 'articlesummaries' %}
        <div class="row">
            <div class="table-first-column">Authors:</div>
            <div class="col-md table-second-column">{{ object.authors }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Year of Publication:</div>
            <div class="col-md table-second-column">{{ object.pub_year }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">DOI:</div>
            {% if object.doi %}
            <div class="col-md table-second-column"><a class="doi-link" href="https://doi.org/{{ object.doi }}" target="_blank">{{ object.doi }}</a></div>
            {% else %} 
            <div class="col-md table-second-column">&#8722;</div>
            {% endif %}
        </div>
        <div class="row">
            <div class="table-first-column">Journal / Conference:</div>
            <div class="col-md table-second-column">{{ object.jour_conf|default:"&#8722;" }}</div>
        </div>

        {% elif appname == 'projectsummaries' %}
        <div class="row">
            <div class="table-first-column">Participating Insitutions:</div>
            <div class="col-md table-second-column">{{ object.institutions|default:"&#8722;" }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Summary Author:</div>
            <div class="col-md table-second-column">{{ object.authors }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Project Website:</div>
            {% if object.url %}
            <div class="col-md table-second-column"><a class="doi-link" href="{{ object.url }}" target="_blank">{{ object.url }}</a></div>
            {% else %} 
            <div class="col-md table-second-column">&#8722;</div>
            {% endif %}
        </div>

        {% elif appname == 'educationalcontent' %}
        <div class="row">
            <div class="table-first-column">Institution:</div>
            <div class="col-md table-second-column">{{ object.institutions|default:"&#8722;" }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Department:</div>
            <div class="col-md table-second-column">{{ object.department|default:"&#8722;" }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Lecturer(s):</div>
            <div class="col-md table-second-column">{{ object.authors }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Year of original Publication:</div>
            <div class="col-md table-second-column">{{ object.pub_year }}</div>
        </div>
        <div class="row">
            <div class="table-first-column">Difficulty:</div>
            <div class="col-md table-second-column">{{ object.difficulty }}</div>
        </div>
        {% endif %}

        <!-- display areas -->
        <div class="row">
            <div class="table-first-column">Areas:</div>
            <div class="col-md table-second-column no-margin-bottom">
                <p class="table-area-listing"><a href="{% url appname|add:'_list' %}?area={{object.area1}}">{{ object.get_area1_display }}</a></p>
                {% if object.area2 %}
                <br>
                <p class="table-area-listing"><a href="{% url appname|add:'_list' %}?area={{object.area2}}">{{ object.get_area2_display }}</a></p>
                {% endif %}
                {% if object.area3 %}
                <br>
                <p class="table-area-listing"><a href="{% url appname|add:'_list' %}?area={{object.area3}}">{{ object.get_area3_display }}</a></p>
                {% endif %}
            </div>
        </div>
    </div>
    
    <hr>

    <!-- text depending on the app -->
    {% if appname == 'articlesummaries' %}
    <div>
        <p class="header-paragraph">Abstract</p>
        <p class="keep-paragraphs">{{ object.abstract }}</p>

        <div class="spacer-div"></div>

        <p class="header-paragraph">Summary</p>
        <p class="keep-paragraphs">{{ object.summary }}</p>
    </div>

    {% elif appname == 'projectsummaries' %}
    <div>
        <p class="header-paragraph">Short Introduction</p>
        <p class="keep-paragraphs">{{ object.introduction }}</p>

        <div class="spacer-div"></div>

        <p class="header-paragraph">Summary</p>
        <p class="keep-paragraphs">{{ object.summary }}</p>
    </div>

    {% elif appname == 'educationalcontent' %}
    <div>
        {% block detail_educationalcontent %}
        {% endblock %}
    </div>

    {% elif appname == 'forum' %}
    <div>
        {% block detail_forum %}
        {% endblock %}
    </div>
    {% endif %}

    <div class="spacer-div"></div>

    <!-- display image and caption if existing -->
    {% if object.image %}
    <div>
        {% if object.caption %}
        <figcaption>Figure: {{ object.caption }}</figcaption>
        {% endif %}
        <img src="{{ object.image.url }}" alt="">
    </div>
    {% endif %}

    <div class="spacer-div"></div>

    <!-- edit & delete button -->
    {% if appname != 'forum' %}
    <div>
        <a class="link-button" href="{% url appname|add:'_update' object.slug %}">Edit</a>
        <a class="link-button" href="{% url appname|add:'_delete' object.slug %}">Delete</a>
    </div>
    {% endif %}
</div>
{% endblock %}

transparency/templates/app_templates/detail_educationalcontent.html
{% extends 'app_templates/detail.html' %} 


{% block detail_educationalcontent %}
<p class="header-paragraph">Course Description</p>
<p class="keep-paragraphs">{{ object.description }}</p>

<div class="spacer-div"></div>

<p class="header-paragraph">Lectures</p>

<!-- Listing of lectures --> 
<ul>
    {% for lecture in lectures %}

    <li class="lecture">
        <div class="float-right-container">
            <div>
                <strong>{{ lecture.title }}</strong>
            </div>
            <div>
                <a class="underlined-link margin-left" href="{% url appname|add:'_updatelecture' object.slug lecture.id %}">Edit</a>
                <a class="underlined-link margin-left" href="{% url appname|add:'_deletelecture' object.slug lecture.id %}">Delete</a>
            </div>                   
        </div>
        <div>
            <p class="keep-paragraphs"">{{ lecture.description }}</p>

            {% if lecture.video %}
            <a class="link-button" href="{{ lecture.video }}" target="_blank">Open video</a>
            {% endif %}
            {% if lecture.file %}
                {% if lecture.video %}
                <br>
                {% endif %}
                <a class="link-button" href="{{ lecture.file.url }}" download>Download PDF</a>
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

<br>
<a class="underlined-link" href="{% url appname|add:'_createlecture' object.slug %}">+ Add course content</a>
{% endblock %}

transparency/templates/app_templates/detail_forum.html
{% extends 'app_templates/detail.html' %} 


{% block detail_forum %}
<ul>
    <!-- Post -->
    <li class="post">
        <div class="float-right-container">
            <div>
                {% if object.url %}
                <a class="doi-link" href="{{ object.url }}" target="_blank"><strong>{{ object.authors }}</strong></a>
                {% else %}
                <strong>{{ object.authors }}</strong>
                {% endif %}
            </div>
            <div>
                <a class="underlined-link margin-left" href="{% url appname|add:'_update' object.slug %}">Edit</a>
                <a class="underlined-link margin-left" href="{% url appname|add:'_delete' object.slug %}">Delete</a>
            </div>                   
        </div>
        <div class="datetimes">
            {{ object.date_post|date:"M j, Y" }} at {{ object.date_post|date:"G:i" }}
            &#8722; Last modified:
            {{ object.date_modified|date:"M j, Y" }} at {{ object.date_modified|date:"G:i" }}
        </div>

        <p class="keep-paragraphs">{{ object.text }}</p>
    </li>


    <!-- Answers --> 
    {% for answer in answers %}
    <li class="post">
        <div class="answer">
            <div class="float-right-container">
                <div>
                    {% if answer.url %}
                    <a class="doi-link" href="{{ answer.url }}" target="_blank"><strong>{{ answer.authors }}</strong></a>
                    {% else %}
                    <strong>{{ answer.authors }}</strong>
                    {% endif %}
                </div>
                <div>
                    <a class="underlined-link margin-left" href="{% url appname|add:'_updateanswer' object.slug answer.id %}">Edit</a>
                    <a class="underlined-link margin-left" href="{% url appname|add:'_deleteanswer' object.slug answer.id %}">Delete</a>
                </div>                   
            </div>
            <div class="datetimes">
                {{ answer.date_post|date:"M j, Y" }} at {{ answer.date_post|date:"G:i" }}
                &#8722; Last modified:
                {{ answer.date_modified|date:"M j, Y" }} at {{ answer.date_modified|date:"G:i" }}
            </div>

            <p class="keep-paragraphs">{{ answer.text }}</p>
        </div>
    </li>
    {% endfor %}

    <li class="post">
        <div class="answer" style="border: none;">
            <p class="header-paragraph">Write an Answer</p>
            <form style="width:100%;" id="add-article-summary" method="post" enctype='multipart/form-data'>{% csrf_token %}
                {{ form.as_p }}   
                <input type="submit" value="Answer">
            </form>
        </div>
    </li>
</ul>
{% endblock %}

transparency/templates/app_templates/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div>
    <div class="container-flex">
        <div class="row">
            <!-- select-menu for area choice on mobile devices -->
            <div class="d-block d-md-none">
                <select class="form-select" onchange="redirectToArea(this.value)">
                    <option value="all">Show all ... ({{num_all_entries}})</option>
                    {% for area in num_entries_area %}    
                        {% if url_area == area.0%}
                        <option value="{{ area.0 }}" selected="selected">{{ area.1 }} ({{area.2}})</option>
                        {% else %}
                        <option value="{{ area.0 }}">{{ area.1 }} ({{area.2}})</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>

            <!-- link menu for area choice on desktop -->
            <div class="area-choice-menu bottom-buffer d-none d-md-block">
                <p class="header-paragraph">Areas</p>
                {% if url_area == 'all' %}
                <a class="area-link active-link" style href="{% url appname|add:'_list' %}?area=all">Show all ... ({{num_all_entries}})</a>
                {% else %}
                <a class="area-link" href="{% url appname|add:'_list' %}?area=all">Show all ... ({{num_all_entries}})</a>
                {% endif %}
                
                {% for area in num_entries_area %}
                    {% if url_area == area.0 %}
                    <a class="area-link active-link" href="{% url appname|add:'_list' %}?area={{ area.0 }}">{{ area.1 }} ({{area.2}})</a>
                    {% else %}
                    <a class="area-link" href="{% url appname|add:'_list' %}?area={{ area.0 }}">{{ area.1 }} ({{area.2}})</a>
                    {% endif %}
                {% endfor %}
            </div>
                
            <div class="col-md">
                <!-- New Summary Button -->
                <a class="link-button d-none d-md-block" href="{% url appname|add:'_create' %}">{{ text_button }}</a>
                <a class="link-button link-button-mobiledevice d-block d-md-none" href="{% url appname|add:'_create' %}">{{ text_button }}</a>

                <!-- Display database entries -->
                {% for obj in page_obj %}
                <div class="collapse-menu">
                    {% if appname == 'forum' %}
                    <a class="modern-collapsible content-padding" href="{% url appname|add:'_detail' obj.slug %}">
                        <div class="plus-button-saver">
                            <strong>{{ obj.title }}</strong>
                            <br>
                            {{ obj.authors }} &#183; {{ obj.date_post|date:"M j, Y" }} at {{ obj.date_post|date:"G:i" }}
                        </div>
                        <div>&#9002;</div>
                    </a>

                    {% else %}
                    <button class="modern-collapsible" type="button" onclick="plusChanger('{{ forloop.counter }}')" value="{{ forloop.counter }}">
                        <div class="plus-button-saver">
                            <strong>{{ obj.title }}</strong>
                            <br>
                            {% if obj.pub_year %}
                                {{ obj.pub_year }} &#183;
                            {% endif %}
                            {{ obj.authors }}
                        </div>
                        <div class="plus-button-x" id="plus-button-{{ forloop.counter }}">+</div>
                    </button>
                    <div class="modern-content">
                        <div class="content-padding">
                            <div>
                                {% if appname == 'articlesummaries' %}
                                    {{ obj.abstract }}
                                {% elif appname == 'projectsummaries' %}
                                    {{ obj.introduction }}
                                {% elif appname == 'educationalcontent' %}
                                    {{ obj.description }}
                                {% endif %}
                            </div>
                            <br>
                            <a class="view-full-link" href="{% url appname|add:'_detail' obj.slug %}">{{ text_viewfull }} ...</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% empty %}
                <p><strong>No entries yet.</strong></p>
                {% endfor %}

                <div class="spacer-div"></div>

                <!-- paginator -->
                {% if num_entries and page_obj.paginator.num_pages > 1 %}
                <div class="paginator-bar">
                    <!-- previous page -->
                    {% if page_obj.number > 1 %}
                    <a href="?area={{ url_area }};page={{ page_obj.number|add:'-1' }}" class="paginator-previous">&lsaquo; Previous</a>
                    {% else %}
                    <a href="?area={{ url_area }};page={{ page_obj.number|add:'-1' }}" class="paginator-previous hidden-link">&lsaquo; Previous</a>
                    {% endif %}

                    <!-- page-choice -->
                    {% for page in page_obj.paginator %}
                        {% if forloop.counter == page_obj.number %}
                        <span class="paginator-current-page">{{ forloop.counter }}</span>
                        {% elif forloop.counter >= page_obj.number|add:'-2' and forloop.counter <= page_obj.number|add:'2'%}
                        <a href="?area={{ url_area }};page={{ forloop.counter }}" class="paginator-pagenum-link">{{ forloop.counter }}</a>
                        {% elif forloop.counter == 1 and page_obj.number != 1 %}
                        <a href="?area={{ url_area }};page={{ forloop.counter }}" class="paginator-pagenum-link">{{ forloop.counter }}</a>
                        {% elif forloop.counter == page_obj.paginator.num_pages and page_obj.number != page_obj.paginator.num_pages %}
                        <a href="?area={{ url_area }};page={{ forloop.counter }}" class="paginator-pagenum-link">{{ forloop.counter }}</a>
                        {% elif forloop.counter == 2 or forloop.counter == page_obj.paginator.num_pages|add:'-1' %}
                        <span>...</span>
                        {% elif forloop.counter == page_obj.paginator.num_pages|add:'-1' %}
                        <span>...</span>
                        {% endif %}
                    {% endfor %}
                    
                    <!-- next page -->
                    {% if page_obj.number < page_obj.paginator.num_pages %}
                    <a href="?area={{ url_area }};page={{ page_obj.number|add:'1' }}" class="paginator-next">Next &rsaquo;</a>
                    {% else %}
                    <a href="?area={{ url_area }};page={{ page_obj.number|add:'1' }}" class="paginator-next hidden-link">Next &rsaquo;</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>


<!-- JavaScript -->
<script>
    // onchange-event for select menu
    function redirectToArea(val) {
        location.href = "{% url appname|add:'_list' %}?area=" + val
    }
</script>

{% if appname != 'forum' %}
<script type="text/javascript" src="{% static 'assets/transparency/js/list_collapsible.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/transparency/js/list_plusChanger.js' %}"></script>
{% endif %}
{% endblock %}